-- Forecast vs Movement — seed the movement mappers from the Jun 2026 workbook.
-- Apply movement_mappers.sql first. Safe to re-run (upsert).

-- customers: 859
insert into public.movement_customer_map (customer, channel, platform) values
  ('Flipkart Internet Pvt. Ltd', 'B2C', 'Flipkart'),
  ('Meesho', 'B2C', 'Meesho'),
  ('Amazon Seller Services Private Limited', 'B2C', 'Amazon'),
  ('Reliance Retail Limited - Jio Mart', 'B2C', 'Jio Mart'),
  ('Flipkart India Private Limited-Alpha', 'B2B', 'Alpha'),
  ('ITC Limited - Dr', 'GT', 'GT'),
  ('Scootsy Logistics Private Limited - Swiggy', 'Qcom', 'Instamart'),
  ('Audentia Tech Ventures Private Limited', 'MT', 'MT'),
  ('Brewbay Innovations Private Limited', 'Growth', 'Growth'),
  ('G.M.Enterprises', 'Growth', 'Growth'),
  ('Bright Lifecare Pvt Ltd - Healthkart', 'B2C', 'Others'),
  ('Getsupp Technologies Private Limited', 'B2C', 'GetsUpp'),
  ('Innovative Retail Concepts Private Limited', 'B2B', 'Big Basket'),
  ('Meolaa E-Commerce Private Limited', 'B2C', 'Others'),
  ('Octavos Enterprise Solutions Private Limited', 'B2C', 'Smytten'),
  ('Popclub Vision Tech Private Limited', 'B2C', 'Pop Club'),
  ('Website Sales - Shopify.Com', 'B2C', 'Website'),
  ('Zepto Private Limited (Kiranakart Technologies Pvt Ltd)', 'Qcom', 'Zepto'),
  ('Ayurhub Incorporation', 'GT', 'GT'),
  ('Bottle Lab Technologies Pvt Ltd(Smart Q Compas Vending Division)', 'Growth', 'Growth'),
  ('Compass India Food Services Private Limited', 'Growth', 'Growth'),
  ('EIH Associated Hotels Limited', 'Growth', 'Growth'),
  ('EIH Associated Hotels Limited - OR', 'Growth', 'Growth'),
  ('EIH Limited - DL', 'Growth', 'Growth'),
  ('EIH Limited - MH', 'Growth', 'Growth'),
  ('Flipkart India Private Limited - Hyperlocal', 'Qcom', 'Flipkart Minutes'),
  ('Golden Jubilee Hotels Private Limited', 'Growth', 'Growth'),
  ('Maruti Trading Company', 'CSD', 'CSD'),
  ('MK Retail Company', 'MT', 'MT'),
  ('Mumtaz Hotels Limited', 'Growth', 'Growth'),
  ('Octavos Enterprise Solutions Private Limited-B2B', 'B2B', 'Smytten'),
  ('Office Depot', 'CSD', 'CSD'),
  ('Parents Agencies', 'Growth', 'Growth'),
  ('Sodexo India Services Pvt Ltd', 'Growth', 'Growth'),
  ('A A Marketing', 'MT', 'MT'),
  ('Aashirwad', 'MT', 'MT'),
  ('Al Fathima General Trading Pvt Ltd', 'MT', 'MT'),
  ('Apollo Healthco Limited', 'MT', 'MT'),
  ('Arambagh Foodmart Private Limited', 'MT', 'MT'),
  ('Avenue E Commerce Limited', 'MT', 'MT'),
  ('Avenue Supermarts Ltd', 'MT', 'MT'),
  ('Bay Leaf Enterprise', 'MT', 'MT'),
  ('Bhomraaj Marketing', 'CSD', 'CSD'),
  ('CPC MASTER CANTEEN -Kadarpur', 'CSD', 'CSD'),
  ('Customer Sales - B2C', 'Growth', 'Growth'),
  ('Dhanya Bazaar Pvt Ltd', 'MT', 'MT'),
  ('Elite Super Market Pvt Ltd', 'MT', 'MT'),
  ('Empire Industries Ltd', 'Growth', 'Growth'),
  ('Focus Hyper Market', 'MT', 'MT'),
  ('Grace Mart Pvt Ltd', 'MT', 'MT'),
  ('Hands On Trades Private Limited - Grofers', 'Qcom', 'Blinkit'),
  ('Happy 7 Days Hypermarket', 'MT', 'MT'),
  ('JSM VT Hospitality Private Limited', 'Growth', 'Growth'),
  ('Jyoti Enterprises', 'MT', 'MT'),
  ('Kalyan Silks Trichur Pvt Ltd', 'MT', 'MT'),
  ('KPN Farm Fresh Pvt Ltd', 'MT', 'MT'),
  ('LMT Hospitality -DMRC', 'Growth', 'Growth'),
  ('Lulu India Shopping Mall Private Limited - Lucknow - 9401', 'MT', 'MT'),
  ('Lulu International Shopping Malls Private Limited - Falcon City - 9420', 'MT', 'MT'),
  ('Lulu International Shopping Malls Private Limited - VR Mall - 9435', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Hyd - 9426', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Kadakampally - 9211', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Palakkad - 9256', 'MT', 'MT'),
  ('Mahalaxmi Enterprises', 'CSD', 'CSD'),
  ('Manya Enterprises', 'CSD', 'CSD'),
  ('Master Bhandar (KPKB) GC CRPF Rangareddy', 'CSD', 'CSD'),
  ('Metro Cash & Carry India Pvt Ltd', 'MT', 'MT'),
  ('Moolans Family Mart - Kothamangalam', 'MT', 'MT'),
  ('Moolans Family Mart - North Paravur', 'MT', 'MT'),
  ('More Retail Limited', 'MT', 'MT'),
  ('Namdhari Agro Fresh Pvt Ltd', 'MT', 'MT'),
  ('Natures Basket Ltd', 'MT', 'MT'),
  ('Nuts N Spices', 'MT', 'MT'),
  ('Octopolis Technologies Pvt Ltd', 'MT', 'MT'),
  ('Om Marketing', 'MT', 'MT'),
  ('Pothys Retail Pvt Ltd - KL', 'MT', 'MT'),
  ('Ratnadeep Retail Pvt Ltd', 'MT', 'MT'),
  ('Ratnadeep Retail Pvt Ltd - National Mart', 'MT', 'MT'),
  ('Reliance Retail Limited', 'MT', 'MT'),
  ('Rozana Rural Commerce Private Limited', 'MT', 'MT'),
  ('RSB Retail India Limited', 'MT', 'MT'),
  ('Sampoorna Retail (India) Pvt Ltd', 'MT', 'MT'),
  ('Sawhney Agencies', 'MT', 'MT'),
  ('Spencer''s Retail Limited', 'MT', 'MT'),
  ('Srinivasa Agencies', 'MT', 'MT'),
  ('SS The  Mart', 'MT', 'MT'),
  ('Subha Enterprises', 'GT', 'GT'),
  ('Supermarket Grocery Supplies Private Limited - Bigbasket', 'B2B', 'Big Basket'),
  ('Suvidha Supermart - Pulse Hospitality Pvt Ltd', 'MT', 'MT'),
  ('Trent Hypermarket Private Limited', 'MT', 'MT'),
  ('Uprising Distribution Co', 'MT', 'MT'),
  ('Ushodaya Super Markets Pvt Ltd', 'MT', 'MT'),
  ('Vijetha Supermarkets Pvt Ltd', 'MT', 'MT'),
  ('Wellness Forever Medicare Ltd', 'MT', 'MT'),
  ('Budget Foods Pvt Ltd - Nesto Hypermarket', 'MT', 'MT'),
  ('Ekaaya Network Private Limited', 'Growth', 'Growth'),
  ('Hospitality Solutions', 'Growth', 'Growth'),
  ('Flipkart India Private Limited - Supermart', 'B2B', 'Supermart'),
  ('DMSL Ventures Private Limited', 'B2B', 'DMSL'),
  ('Dreamplug Technologies Pvt Ltd (Cred)', 'B2C', 'CRED'),
  ('Halfcirclefull Ecommerce Llp', 'B2C', 'Others'),
  ('Ashok Anil Enterprises LLP - Suvidha', 'MT', 'MT'),
  ('Lulu International Shopping Malls Private Limited - M5 - Electronic City - 9445', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Calicut - 9257', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Coimbatore - 9416', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Ernakulam - 9201', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Global Mall - 9411', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Kochi - 9240', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Kottiyam - 9285', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd - Thrissur - 9260', 'MT', 'MT'),
  ('GZakya-Cult Neo', 'Growth', 'Growth'),
  ('Vijya Trading Co - Rishikesh', 'GT', 'GT'),
  ('Vas Nutracare', 'GT', 'GT'),
  ('Global Office Needs', 'Growth', 'Growth'),
  ('PVR Inox Limited', 'Growth', 'Growth'),
  ('Wilco Publishing House -Dr', 'Growth', 'Growth'),
  ('4Syz Infotech Solutions Private Limited', 'Growth', 'Growth'),
  ('Kiaan Fitness', 'Growth', 'Growth'),
  ('Cultfit Healthcare Pvt Ltd', 'Growth', 'Growth'),
  ('F2 Fun And Fitness (India) Private Limited', 'Growth', 'Growth'),
  ('Nutrabay Retail Pvt Ltd', 'B2B', 'Nutrabay'),
  ('Aaj Enterprises', 'GT', 'GT'),
  ('Casino Air Catering & Flight Services-TS', 'Growth', 'Growth'),
  ('Eden R Mart', 'MT', 'MT'),
  ('Fleet Labs Technologies Pvt Ltd - Apna Mart', 'MT', 'MT'),
  ('Indian Naval Canteen Service -DL', 'CSD', 'CSD'),
  ('Lulu International Shopping Malls Pvt Ltd - Kottayam - 9226', 'MT', 'MT'),
  ('Moolans Family Mart - Angamaly', 'MT', 'MT'),
  ('Paras Rajendra Gathani - Versatile Service', 'Growth', 'Growth'),
  ('Amala Earth Private Limited', 'B2C', 'Others'),
  ('Semolina Kitchens Private Limited - TFS(AS)', 'Growth', 'Growth'),
  ('Semolina Kitchens Private Limited - TFS(GJ)', 'Growth', 'Growth'),
  ('Semolina Kitchens Private Limited - TFS(KL)', 'Growth', 'Growth'),
  ('Semolina Kitchens Private Limited - TFS(MH)', 'Growth', 'Growth'),
  ('Semolina Kitchens Private Limited - TFS(UP)', 'Growth', 'Growth'),
  ('Travel Food Services Limited', 'Growth', 'Growth'),
  ('Hyuga Ecommerce Ventures Pvt Ltd', 'B2B', 'Hyuga'),
  ('Myntra Jabong India Private Limited', 'B2C', 'Myntra'),
  ('Wagonmart Calicut Retail Llp', 'MT', 'MT'),
  ('Alekos Technologies India Private Limited', 'Growth', 'Growth'),
  ('Malik Agencies', 'Growth', 'Growth'),
  ('Sai Foods Private Limited', 'Growth', 'Growth'),
  ('Lulu International Shopping Malls Pvt Ltd - Thrissur - 9216', 'MT', 'MT'),
  ('Fitness Factory', 'MT', 'MT'),
  ('White Water Retail Private Limited', 'GT', 'GT'),
  ('Eden General Stores', 'MT', 'MT'),
  ('Patel Retail Limited', 'MT', 'MT'),
  ('Haiko Supermarket', 'MT', 'MT'),
  ('Canteen Stores Department - CSD', 'CSD', 'CSD'),
  ('Hind Medicos', 'GT', 'GT'),
  ('Jagdamba Enterprises', 'GT', 'GT'),
  ('Casino Air Caterers & Flight Services-Calicut', 'Growth', 'Growth'),
  ('Casino Air Caterers & Flight Services-Coimbatore', 'Growth', 'Growth'),
  ('Casino Air Caterers & Flight Services-GJ', 'Growth', 'Growth'),
  ('Casino Air Catering & Flight Services-MH', 'Growth', 'Growth'),
  ('Interglobe Aviation Ltd - Dr', 'Growth', 'Growth'),
  ('LSG Sky Chefs (India) Private Ltd-TL', 'Growth', 'Growth'),
  ('Pal Lifeware Pvt Ltd', 'MT', 'MT'),
  ('Pradeep Air Catering', 'Growth', 'Growth'),
  ('Raja Motels & Hotels India Pvt Ltd - Ritz Hotel', 'Growth', 'Growth'),
  ('Taj Sats Air Catering Ltd - DL', 'Growth', 'Growth'),
  ('Taj Sats Air Catering Ltd - MH', 'Growth', 'Growth'),
  ('Narangs International Hotels Pvt Ltd-DL', 'Growth', 'Growth'),
  ('Narangs International Hotels Pvt Ltd-MH', 'Growth', 'Growth'),
  ('Oberoi Flight Services - MH', 'Growth', 'Growth'),
  ('Oberoi Flight Services-DL', 'Growth', 'Growth'),
  ('Taj Sats Air Catering Ltd - KA', 'Growth', 'Growth'),
  ('Taj Sats Air Catering Ltd - TN', 'Growth', 'Growth'),
  ('Taj Sats Air Catering Ltd - WB', 'Growth', 'Growth'),
  ('Dhanya Consumers Pvt Ltd', 'MT', 'MT'),
  ('Jogo Technologies Private Limited', 'Growth', 'Growth'),
  ('Rail Food & Services', 'Growth', 'Growth'),
  ('Burrito Restaurants Private Limited', 'Growth', 'Growth'),
  ('Burrito Restaurants Private Limited - MH', 'Growth', 'Growth'),
  ('Chaman Traders', 'GT', 'GT'),
  ('Diverse Retails Private Limited - Cult', 'Growth', 'Growth'),
  ('M/S Cozy Cure Nutrition', 'MT', 'MT'),
  ('Lo Fresh Foods Private Limited', 'Growth', 'Growth'),
  ('Alteria Venture Partners LLP', 'MT', 'MT'),
  ('Coffee Day Global Limited', 'Growth', 'Growth'),
  ('Protein World', 'MT', 'MT'),
  ('Sunshine Teahouse Private Limited', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited - Akasa Air', 'Growth', 'Growth'),
  ('Leela Enterprises', 'Growth', 'Growth'),
  ('Poptech Growth Private Limited', 'B2C', 'Pop Club'),
  ('Gayatri Agency', 'Growth', 'Growth'),
  ('Om Enterprises - Pune', 'Growth', 'Growth'),
  ('Orbit Resorts Limited - HR', 'Growth', 'Growth'),
  ('Pomac Hypermarket Pvt Ltd', 'MT', 'MT'),
  ('CPC Master Canteen 8th RES BN Jaipur', 'CSD', 'CSD'),
  ('Gamini Nagabhushanam Enterprises', 'MT', 'MT'),
  ('Jeyachandran Retail Private Limited', 'MT', 'MT'),
  ('Kendriya Police Kalyan Bhandar (Master Bhandar) Gc Crpf - Pallipuram', 'CSD', 'CSD'),
  ('Master Canteen CPC SSB FHQ', 'CSD', 'CSD'),
  ('Merabo Labs Private Limited', 'MT', 'MT'),
  ('Moolans Family Mart - Perumbavoor', 'MT', 'MT'),
  ('Optival Health Solutions Private Limited', 'MT', 'MT'),
  ('Q-Mart Retail Ltd', 'MT', 'MT'),
  ('Red Basil Technologies Private Limited', 'Growth', 'Growth'),
  ('Adnixpro Private Limited', 'Growth', 'Growth'),
  ('R.N. Enterprises', 'MT', 'MT'),
  ('Red Rose Super Market', 'MT', 'MT'),
  ('TSG Fitness Corner', 'Exports', 'Export'),
  ('Army Eastern Command', 'Growth', 'Growth'),
  ('Zain Traders & Co', 'MT', 'MT'),
  ('Snowman Logistics Limited', 'Growth', 'Growth'),
  ('Atlas Distributors Private Limited', 'Growth', 'Growth'),
  ('Noble Sales', 'Growth', 'Growth'),
  ('Value Express Corporate Services', 'Growth', 'Growth'),
  ('Nutrition & Health Foods', 'MT', 'MT'),
  ('Central Police Canteen - New Delhi', 'CSD', 'CSD'),
  ('Master Bhandar CRPF HQ CGO - DL', 'CSD', 'CSD'),
  ('Mutant Nation', 'MT', 'MT'),
  ('Nutrition House', 'MT', 'MT'),
  ('Sachdeva & Co', 'GT', 'GT'),
  ('Radhika Traders', 'MT', 'MT'),
  ('Urban Life Trading W.L.L', 'Exports', 'Export'),
  ('Quick Bite', 'Growth', 'Growth'),
  ('M/S Roosi Brothers - Umesh Chandha', 'Growth', 'Growth'),
  ('Cult Neo', 'Growth', 'Growth'),
  ('EIH Associated Hotels Limited - RJ', 'Growth', 'Growth'),
  ('SS The Mart', 'MT', 'MT'),
  ('NPI', 'NPI', 'NPI'),
  ('Avenue E-Commerce Ltd', 'MT', 'MT'),
  ('NESTO HYPERMARKET', 'MT', 'MT'),
  ('KIRANAKART TECHNOLOGIES PVT LTD', 'Qcom', 'Zepto'),
  ('Scootsy Logistics Private Ltd', 'Qcom', 'Instamart'),
  ('More Retail Private Limited', 'MT', 'MT'),
  ('Namdhari Agrofresh Pvt Ltd', 'MT', 'MT'),
  ('MOOLANS FAMILY MART - NORTH PRAVUR', 'MT', 'MT'),
  ('Reliance Retail Limited - Tamil Nadu', 'MT', 'MT'),
  ('CSD', 'CSD', 'CSD'),
  ('Lo Fresh Foods Private Limited-BLR', 'Growth', 'Growth'),
  ('Sameer Afsal', 'Sample', 'Sample'),
  ('Lulu Hypermarket- Lucknow', 'MT', 'MT'),
  ('AA Marketing', 'MT', 'MT'),
  ('Go chai beverage pvt ltd.', 'Growth', 'Growth'),
  ('Go Chai Beverages Pvt Ltd', 'Growth', 'Growth'),
  ('Lulu Hypermarket ,Trivandrum', 'MT', 'MT'),
  ('Flipkart Replication - Chennai', 'B2C', 'Replication'),
  ('Flipkart Replication - Bhiwandi', 'B2C', 'Replication'),
  ('Flipkart Replication - Malur BTS', 'B2C', 'Replication'),
  ('Flipkart Replication - Hyderabad', 'B2C', 'Replication'),
  ('4SYZ INFOTECH SOLUTIONS PVT. LTD', 'Growth', 'Growth'),
  ('Flipkart Replication - Ahmedabad', 'B2C', 'Replication'),
  ('SPROUTLIFE FOODS PRIVATE LIMITED (HO)', 'Sample', 'Sample'),
  ('Taj SATS AIR CATERING LTD BLR', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (GOOGLE - FLEX SPACE - BLR)', 'Growth', 'Growth'),
  ('Lo Fresh Foods Private Limited-DEL', 'Growth', 'Growth'),
  ('Sodexo India Services Pvt Ltd (Kyoto)', 'Growth', 'Growth'),
  ('Travel Food Services Limited-TFS CHENNAI', 'Growth', 'Growth'),
  ('Lulu Daily, M5 Ecity Mall', 'MT', 'MT'),
  ('Lulu Hypermarket-Edapally', 'MT', 'MT'),
  ('Sunshine Teahouse Private Limited- BLR', 'Growth', 'Growth'),
  ('DHI office', 'Sample', 'Sample'),
  ('PHARMED LTD', 'Gifting', 'Gifting'),
  ('Paras Rajendra Gathani (VERSATILE SERVICES)', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED', 'Growth', 'Growth'),
  ('KENDRIYA POLICE KALYAN BHANDAR (MASTER BHANDAR) GC CRPF PALLIPURAM', 'CSD', 'CSD'),
  ('Lulu Daily, Maradu, Kochi', 'MT', 'MT'),
  ('LMT HOSPITALITY - DMRC', 'Growth', 'Growth'),
  ('Global Office Needs-BLR', 'Growth', 'Growth'),
  ('MASTER CANTEEN SSB FHQ', 'CSD', 'CSD'),
  ('TajSATS Air Catering Ltd- DELHI', 'Growth', 'Growth'),
  ('DHANYA BAZAR PVT LTD', 'MT', 'MT'),
  ('Pothys Retail Private Limited', 'MT', 'MT'),
  ('KPN Farm Fresh Private Limited', 'MT', 'MT'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (OPAL)', 'Growth', 'Growth'),
  ('Sunshine Teahouse Private Limited - Gurgaon', 'Growth', 'Growth'),
  ('Lulu Hypermarket, Kottayam', 'MT', 'MT'),
  ('Demo Customer', 'Sample', 'Sample'),
  ('Lulu Hypermarket- Hyderabad', 'MT', 'MT'),
  ('BREWBAY INNOVATIONS PRIVATE LIMITED-abcoffee Mumbai', 'Growth', 'Growth'),
  ('BREWBAY INNOVATIONS PRIVATE LIMITED- abcoffee BLR', 'Growth', 'Growth'),
  ('BREWBAY INNOVATIONS PRIVATE LIMITED- abcoffee HYD', 'Growth', 'Growth'),
  ('SEMOLINA KITCHENS PVT LTD-TFS LUCKNOW', 'Growth', 'Growth'),
  ('Natures Basket Limited', 'MT', 'MT'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED ( Carina Building)', 'Growth', 'Growth'),
  ('Taj SATS AIR CATERING LTD CCU', 'Growth', 'Growth'),
  ('Burrito Restaurant Pvt. Ltd.- CHENNAI', 'Growth', 'Growth'),
  ('BURRITO RESTAURANTS PRIVATE LIMITED-HYD', 'Growth', 'Growth'),
  ('Ratnadeep Retail Pvt Ltd -NATIONAL MART', 'MT', 'MT'),
  ('VIJETHA SUPERMARKETS PVT.LTD', 'MT', 'MT'),
  ('Spencers Retail Limited', 'MT', 'MT'),
  ('CASINO AIR CATERERS & FLIGHT  SERVICES-HYD', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-(SIG.C)', 'Growth', 'Growth'),
  ('Trruu Global Brands LLP - Bangalore', 'Growth', 'Growth'),
  ('Mantri Square Mall', 'MT', 'MT'),
  ('Customer Samples - B2C', 'Sample', 'Sample'),
  ('PABBA JYOTHI- Cult Nagole', 'Growth', 'Growth'),
  ('ITC Limited', 'GT', 'GT'),
  ('EIH Limited', 'Growth', 'Growth'),
  ('EIH Limited -New Delhi', 'Growth', 'Growth'),
  ('Taj SATS AIR CATERING LTD MAA', 'Growth', 'Growth'),
  ('Cult Neo Gym-DL', 'Growth', 'Growth'),
  ('Travel Food Services Limited-TFS Bengaluru', 'Growth', 'Growth'),
  ('NOBLE SALES- ITC Hotel Mumbai', 'Growth', 'Growth'),
  ('Sunshine Teahouse Private Limited- BOM', 'Growth', 'Growth'),
  ('Sodexo India Services Pvt Ltd (Kyoto East)', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED  CAFE COFFEE DAY-DIVISION Chennai', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED  CAFE COFFEE DAY-DIVISION BLR', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED  CAFE COFFEE DAY-DIVISION-BOM', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED  CAFE COFFEE DAY-DIVISION-CCU', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED  CAFE COFFEE DAY-DIVISION', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED  CAFE COFFEE DAY-DIVISION- HYD', 'Growth', 'Growth'),
  ('Lulu Hypermarket , Bangalore', 'MT', 'MT'),
  ('Lulu Daily', 'MT', 'MT'),
  ('BREWBAY INNOVATIONS PRIVATE LIMITED-abcoffee Gurgaon', 'Growth', 'Growth'),
  ('Cult Gym Hoodi', 'Growth', 'Growth'),
  ('Cult Gym Kundalahalli', 'Growth', 'Growth'),
  ('HRX Gym JP Nagar', 'Growth', 'Growth'),
  ('HRX Gym Kothapet', 'Growth', 'Growth'),
  ('HRX Gym RR Nagar', 'Growth', 'Growth'),
  ('MARV FITNESS CULTURE LLP', 'Growth', 'Growth'),
  ('HRX Gym Begur', 'Growth', 'Growth'),
  ('HRX Gym TC Palya', 'Growth', 'Growth'),
  ('Cult Neo Gym Nagarbhavi', 'Growth', 'Growth'),
  ('Cult Neo Gym Hosa Road', 'Growth', 'Growth'),
  ('cult neo gym Bhattarahalli', 'Growth', 'Growth'),
  ('Cult neo gym Chandapura', 'Growth', 'Growth'),
  ('Cult Neo Gym Vidyaranyapura', 'Growth', 'Growth'),
  ('cult neo gym Mathikere', 'Growth', 'Growth'),
  ('Cult Neo Gym Andrahalli', 'Growth', 'Growth'),
  ('Cult Neo Gym - Hyd', 'Growth', 'Growth'),
  ('PARADISE POWER PROJECTS (Cult Gym )', 'Growth', 'Growth'),
  ('Cult neo gym Ambedkar Road', 'Growth', 'Growth'),
  ('Cult neo gym Uttam Nagar', 'Growth', 'Growth'),
  ('Cult Neo Gym, NIT Faridabad', 'Growth', 'Growth'),
  ('Cult neo gym Mahavir Enclave', 'Growth', 'Growth'),
  ('Cult Neo Gym Sector 10A', 'Growth', 'Growth'),
  ('Cult neo gym Sector 62 Gurugram', 'Growth', 'Growth'),
  ('Cult Neo Gym Vasai', 'Growth', 'Growth'),
  ('Cult Neo Gym Virar West', 'Growth', 'Growth'),
  ('Cult Neo Gym Alwal', 'Growth', 'Growth'),
  ('Cult Neo Gym Amberpet', 'Growth', 'Growth'),
  ('Cult Neo Gym Boduppal', 'Growth', 'Growth'),
  ('Cult Neo Gym Uppal', 'Growth', 'Growth'),
  ('cult neo gym Santosh Nagar', 'Growth', 'Growth'),
  ('Cult Neo Gym B N Reddy - Telangana', 'Growth', 'Growth'),
  ('Cult Neo Gym Kothapet - Telangana', 'Growth', 'Growth'),
  ('Cult Neo Gym AS Rao Nagar - Telangana', 'Growth', 'Growth'),
  ('ANVIRA VENTURES', 'Growth', 'Growth'),
  ('GRACE MART PRIVATE LIMITED', 'MT', 'MT'),
  ('Ashutosh patil', 'Sample', 'Sample'),
  ('Nuts & Spices', 'Sample', 'Sample'),
  ('Amazon Replication -PAX1', 'B2C', 'Replication'),
  ('Amazon - Replication - BOM5', 'B2C', 'Replication'),
  ('Amazon - Replication - CCX1', 'B2C', 'Replication'),
  ('Amazon - Replication - CJB1', 'B2C', 'Replication'),
  ('Amazon - Replication - HYD3', 'B2C', 'Replication'),
  ('Amazon - Replication - LKO1', 'B2C', 'Replication'),
  ('Amazon - Replication - JPX1', 'B2C', 'Replication'),
  ('Amazon - Replication - AMD2', 'B2C', 'Replication'),
  ('Amazon Replication -IDX2', 'B2C', 'Replication'),
  ('M.K.Retail Company', 'MT', 'MT'),
  ('Mohan Raj', 'Sample', 'Sample'),
  ('VALUE EXPRESS CORPORATE SERVICES -HYD', 'Growth', 'Growth'),
  ('Perfect point-BLR', 'Growth', 'Growth'),
  ('Landmark services india pvt ltd -BLR', 'Growth', 'Growth'),
  ('USHODAYA SUPERMARKETS PVT LTD', 'MT', 'MT'),
  ('NARANGS INTERNATIONAL HOTELS PVT. LTD.', 'Growth', 'Growth'),
  ('Bigbasket - supermarket grocery su pvt ltd', 'B2B', 'Big Basket'),
  ('ORBIT RESORTS LTD-Unit : Trident, Gurgaon', 'Growth', 'Growth'),
  ('SPROUTLIFE FOODS PRIVATE LIMITED -HO', 'Sample', 'Sample'),
  ('Lions Club of Bangalore Megacity', 'Sample', 'Sample'),
  ('Play On Fitness', 'Growth', 'Growth'),
  ('Lulu Hypermarket, Palakkad', 'MT', 'MT'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED HYD FLEX', 'Growth', 'Growth'),
  ('Amazon - Replication - MAA4', 'B2C', 'Replication'),
  ('Amazon - Replication - HYD8', 'B2C', 'Replication'),
  ('Trruu Global Brands LLP - Delhi', 'Growth', 'Growth'),
  ('Trruu Global Brands LLP - Mumbai', 'Growth', 'Growth'),
  ('G M ENTERPRISES', 'Growth', 'Growth'),
  ('Naveen Gaurav', 'Sample', 'Sample'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED -GGN', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (GOOGLE-SIGB)', 'Growth', 'Growth'),
  ('Lulu Daily, Lulu Connect, Reo', 'MT', 'MT'),
  ('Sodexo India Services Private Limited-TS', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited - Akasa Air (AMD)', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited - Akasa Air (BOM)', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited - Akasa Air (DEL)', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited- GOA', 'Growth', 'Growth'),
  ('VALUE ZONE HYPERMART', 'MT', 'MT'),
  ('SPROUTLIFE FOODS PRIVATE LIMITED', 'Sample', 'Sample'),
  ('JEYACHANDRAN RETAIL PRIVATE LIMITED -RAMACHANDRAN', 'MT', 'MT'),
  ('Flipkart Replication - Sanpka', 'B2C', 'Replication'),
  ('Flipkart Replication -Jaipur NLFC 01', 'B2C', 'Replication'),
  ('LuLu Express Freshmarket-Thrissur', 'MT', 'MT'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-CJB', 'Growth', 'Growth'),
  ('DHANYA CONSUMERS PRIVATE LIMITED', 'MT', 'MT'),
  ('HOSPITALITY SOLUTIONS-GOA', 'Growth', 'Growth'),
  ('OPTIVAL HEALTH SOLUTIONS', 'MT', 'MT'),
  ('REd Rose Mart', 'MT', 'MT'),
  ('Lulu Hypermarket,Thrissur', 'MT', 'MT'),
  ('Lulu Daily - Kottiyam', 'MT', 'MT'),
  ('SNV Aviation Private Limited (Akasa Air BLR)', 'Growth', 'Growth'),
  ('EMPIRE INDUSTRIES LTD-VENDING DIVISION-BLR', 'Growth', 'Growth'),
  ('MMOLANS FAMILY TRUST', 'MT', 'MT'),
  ('CENTRAL POLICE CANTEEN', 'CSD', 'CSD'),
  ('TRAVEL FOOD SERVICES LIMITED-TFS  Bhubaneshwar', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-GGN', 'Growth', 'Growth'),
  ('EMPIRE INDUSTRIES LTD-VENDING DIVISION-PUNE', 'Growth', 'Growth'),
  ('EMPIRE INDUSTRIES LTD-VENDING DIVISION-BOM', 'Growth', 'Growth'),
  ('MS ROOSI BROTHERS', 'Growth', 'Growth'),
  ('HAPPY 7 DAYS HYPERMARKET LLP', 'MT', 'MT'),
  ('Burrito Restaurant Pvt. Ltd.- Pune', 'Growth', 'Growth'),
  ('OPTIVAL HEALTH SOLUTIONS PVT LTD', 'MT', 'MT'),
  ('MS JSM VT HOSPITALITY PVT LTD', 'MT', 'MT'),
  ('Avenue E Commerce Limited - Chennai', 'MT', 'MT'),
  ('Jiomart - Mumbai', 'B2C', 'Jio Mart'),
  ('Jiomart - Hyderabad', 'B2C', 'Jio Mart'),
  ('Jiomart - Kolkata', 'B2C', 'Jio Mart'),
  ('Officer Commanding, Field Supply Depot ASC (Dahung)', 'CSD', 'CSD'),
  ('Kalyan Hypermarket', 'MT', 'MT'),
  ('ARAMBAGH FOOD MART', 'MT', 'MT'),
  ('ITC LIMITED, FOODS DIVISION', 'Sample', 'Sample'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (GOC)', 'Growth', 'Growth'),
  ('Lulu Hypermarket, Coimbatore', 'MT', 'MT'),
  ('Seven - 11 Sample', 'Sample', 'Sample'),
  ('Ashok Anil Enterprises Llp', 'MT', 'MT'),
  ('Sapna Panda', 'Sample', 'Sample'),
  ('Sodexo India Services Pvt Ltd-TS', 'Growth', 'Growth'),
  ('Trident Hyderabad-(A unit of Golden Jubilee Hotels Pvt Ltd)', 'Growth', 'Growth'),
  ('Meeran Syed', 'Sample', 'Sample'),
  ('Sachdeva & Co.', 'GT', 'GT'),
  ('CPC Master Canteen 8th RES BN', 'CSD', 'CSD'),
  ('Flipkart Replication - Kolkata (uluberia)', 'B2C', 'Replication'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (GOOGLE-OMEGA)', 'Growth', 'Growth'),
  ('Deepak Chaudhari', 'Sample', 'Sample'),
  ('OM ENTERPRISES-PUNE', 'Growth', 'Growth'),
  ('PERFECT POINT-HYD', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED- HYD', 'Growth', 'Growth'),
  ('MS Leela Enterprises', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (RMZ)', 'Growth', 'Growth'),
  ('WELLNESS FOREVER MEDICARE LIMITED ZEDC', 'MT', 'MT'),
  ('Ankit Dubey', 'Sample', 'Sample'),
  ('Officer Commanding, Field Supply Depot ASC (Srinagar)', 'CSD', 'CSD'),
  ('EIH Associated Hotels Limited-Udaipur', 'Growth', 'Growth'),
  ('CALM SUN WELLNESS LLP', 'Growth', 'Growth'),
  ('Aahan Shah', 'Sample', 'Sample'),
  ('Kailash Gofane', 'Sample', 'Sample'),
  ('SNOWMAN LOGISTICS LIMITED- Tim Horton', 'Growth', 'Growth'),
  ('NOWMAN LOGISTICS LIMITED- Tim Horton Derabassi', 'Growth', 'Growth'),
  ('SNOWMAN LOGISTICS LIMITED- Tim Horton (Mumbai)', 'Growth', 'Growth'),
  ('Snowman Logistics Limited-Tim Hortons (Palwal)', 'Growth', 'Growth'),
  ('Camlin Fine sciences', 'GT', 'GT'),
  ('GAYATRI AGENCY- Jabalpur', 'Growth', 'Growth'),
  ('Nutriton 8', 'Growth', 'Growth'),
  ('Pranoy Radiya', 'Sample', 'Sample'),
  ('Officer Commanding, Field Supply Depot ASC (Leh)', 'CSD', 'CSD'),
  ('Sodexo India Services Private Limited-GA', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited -(HYD)', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited-PNQ', 'Growth', 'Growth'),
  ('BURRITO RESTAURANTS PRIVATE LIMITED-BLR', 'Growth', 'Growth'),
  ('EIH Limited - KA', 'Growth', 'Growth'),
  ('Sai Chaithanya Enterprises', 'Growth', 'Growth'),
  ('M/S Suresh Provision Stores', 'Growth', 'Growth'),
  ('Sadguru Enterprises', 'Growth', 'Growth'),
  ('Ganapati Fashions Ltd', 'Growth', 'Growth'),
  ('Goal Fitness Centre', 'Growth', 'Growth'),
  ('Wilco Publishing House', 'Growth', 'Growth'),
  ('Ekaagra Ostalaritza Private Limited', 'Growth', 'Growth'),
  ('Venzop Foods Private Limited', 'Growth', 'Growth'),
  ('Brijesh Trading House', 'Growth', 'Growth'),
  ('Bansal Traders', 'Growth', 'Growth'),
  ('Barista Coffee Company Limited', 'Growth', 'Growth'),
  ('Just Udo Aviation Private Limited - FLY91', 'Growth', 'Growth'),
  ('Fitness Aqua', 'GT', 'GT'),
  ('Kendriya Police Kalyan Bhandar Master Bhandar - Peringome', 'CSD', 'CSD'),
  ('Bansal Super Market', 'MT', 'MT'),
  ('Saravana Stores (Tex)', 'MT', 'MT'),
  ('Shubham K-Mart Private Limited', 'MT', 'MT'),
  ('Vijayalakshmi Enterprises', 'MT', 'MT'),
  ('Magson Retail And Distribution Limited', 'MT', 'MT'),
  ('7-India Convenience Retail Limited', 'MT', 'MT'),
  ('Pothys Retail Pvt Ltd - TN', 'MT', 'MT'),
  ('Goodwill Enterprises LLP', 'MT', 'MT'),
  ('Kunnil Super Market', 'MT', 'MT'),
  ('Elite Supermarket Pvt Ltd', 'MT', 'MT'),
  ('Lulu Warehouse , Bangalore', 'MT', 'MT'),
  ('MAGSON RETAIL AND DISTRIBUTION LTD', 'MT', 'MT'),
  ('Pothys Private Limited', 'MT', 'MT'),
  ('Avenue Supermarts Ltd - Virugambakkam', 'MT', 'MT'),
  ('Lulu Hypermarket , Trivandrum', 'MT', 'MT'),
  ('Barista Coffee Company Limited-GGN', 'Growth', 'Growth'),
  ('EKAAGRA OSTALARITZA PVT LTD', 'Growth', 'Growth'),
  ('BANSAL TRADERS-AMRITSAR', 'Growth', 'Growth'),
  ('ALEKOS TECHNOLOGIES INDIA PVT LTD', 'Growth', 'Growth'),
  ('Just Udo Aviation Pvt Ltd (Fly91)', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-HYD', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-PUNE', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (GOOGLE CONNECT (BLOCK E)', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-FC MADRAS', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-BOM', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited-COK', 'Growth', 'Growth'),
  ('Sai Chaithanya Enterprises -BLR', 'Growth', 'Growth'),
  ('MS SURESH PROVISION STORES', 'Growth', 'Growth'),
  ('Sodexo India Services Pvt Ltd-MUMBAI', 'Growth', 'Growth'),
  ('THE OBEROI BENGALURU-EIH LIMITED', 'Growth', 'Growth'),
  ('Casino Air Caterers & Flight Services-PUNE', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED -MAA', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-NOIDA', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-EGL', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-MTP', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-HYD', 'Growth', 'Growth'),
  ('Cozy Care Nutrition', 'Growth', 'Growth'),
  ('EIH Associated Hotels Limited-Bhubaneswar', 'Growth', 'Growth'),
  ('Amazon - Replication - BOM7', 'B2C', 'Replication'),
  ('KUNNIL SUPERMARKET', 'MT', 'MT'),
  ('KUNNIL HYPER MARKET', 'MT', 'MT'),
  ('SARAVANA STORES(TEX)', 'MT', 'MT'),
  ('Cult neo gym JP Nagar 8th Phase', 'Growth', 'Growth'),
  ('TRAVEL FOOD SERVICES LIMITED-TFS  Kolkata', 'Growth', 'Growth'),
  ('SHUBHAM K MART PVT.LTD', 'MT', 'MT'),
  ('INSTA TOURISM PRIVATE LIMITED', 'MT', 'MT'),
  ('HIND MEDICOSE', 'GT', 'GT'),
  ('BRIJESH TRADING HOUSE-JAIPUR', 'Growth', 'Growth'),
  ('UNICORN ENTERPRISES', 'MT', 'MT'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-DLF', 'Growth', 'Growth'),
  ('Hyugalife', 'B2C', 'Hyugalife'),
  ('Akshat Traders', 'Growth', 'Growth'),
  ('Thrive Ventures', 'Growth', 'Growth'),
  ('Trruu Global Brands LLP', 'Growth', 'Growth'),
  ('Shree Jai Jagadamba', 'Growth', 'Growth'),
  ('Taj Sats Air Catering Ltd - GA', 'Growth', 'Growth'),
  ('Grape Events Private Limited', 'Growth', 'Growth'),
  ('Gochai Beverages Private Limited', 'Growth', 'Growth'),
  ('Headquarters Northern Command (ST)', 'Growth', 'Growth'),
  ('Imagicaaworld Entertainment Limited', 'Growth', 'Growth'),
  ('K.Sons Marketing', 'Growth', 'Growth'),
  ('Bangalore International Airport Limited', 'Growth', 'Growth'),
  ('Jainsons Departmental Stores', 'Growth', 'Growth'),
  ('Snowman Logistics Limited-AGCIPL', 'Growth', 'Growth'),
  ('Vatika Hotels Private Limited', 'Growth', 'Growth'),
  ('Razorpay Software Limited-Dr', 'Growth', 'Growth'),
  ('R & R Consulting', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks And Technologies Llp', 'Growth', 'Growth'),
  ('Palash', 'MT', 'MT'),
  ('Kunnil Margin Free Hyper Market (Nedumangad, 695541)', 'MT', 'MT'),
  ('Margin Free Market (Thiruvananthapuram, 695015)', 'MT', 'MT'),
  ('Foodstories Private Limited', 'MT', 'MT'),
  ('The Power Sports Nutrition', 'MT', 'MT'),
  ('Curioso Fashions Private Limited', 'B2C', 'Pop Club'),
  ('Flipkart Replication -Coimbatore 01 Warehouse', 'B2C', 'Replication'),
  ('ELITE FITNESS AND ENTERTAINMENT PVT LTD', 'Growth', 'Growth'),
  ('Manish Tyagi', 'Sample', 'Sample'),
  ('PARABRAHMA VICTORY VENTURES PRIVATE LIMITED', 'Growth', 'Growth'),
  ('Sodexo India Services Private Limited', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED - Flame University', 'Growth', 'Growth'),
  ('Serene Vibes Private Ltd', 'MT', 'MT'),
  ('India Forms Centre Private Limited-KOLKATA', 'Growth', 'Growth'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED- Microsoft', 'Growth', 'Growth'),
  ('Sodexo India Services Pvt Ltd-WB', 'Growth', 'Growth'),
  ('GRAND IMPERIAL FITNESS LLP', 'Growth', 'Growth'),
  ('Ms IMAGICAAWORLD ENTERTAINMENT LTD', 'Growth', 'Growth'),
  ('Seventeen Event', 'Growth', 'Growth'),
  ('Keyur Shah', 'Sample', 'Sample'),
  ('AKSHAT TRADERS - INDORE', 'Growth', 'Growth'),
  ('cult neo gym Dasarahalli', 'Growth', 'Growth'),
  ('Customer Samples - B2C - Tamil Nadu', 'Sample', 'Sample'),
  ('Export Sathi', 'Export', 'Export'),
  ('Vivek Bobade', 'Sample', 'Sample'),
  ('MS ISHVA ENTERPRISES', 'Growth', 'Growth'),
  ('Balram Singh Yadav', 'Sample', 'Sample'),
  ('Ashwin', 'Sample', 'Sample'),
  ('Champa Das', 'Sample', 'Sample'),
  ('D.yadav', 'Sample', 'Sample'),
  ('Nilanchal Nayak', 'Sample', 'Sample'),
  ('Mukesh Sharma', 'Sample', 'Sample'),
  ('Rakesh Salaria', 'Sample', 'Sample'),
  ('Vikrant Chaudhary', 'Sample', 'Sample'),
  ('Hemant Anand', 'Sample', 'Sample'),
  ('YUVARAJ A', 'Sample', 'Sample'),
  ('Harpreet Singh Chahal', 'Sample', 'Sample'),
  ('Phoenix Market City', 'Sample', 'Sample'),
  ('THAKAR FITNESS LLP', 'Growth', 'Growth'),
  ('TRIUMFIT', 'Growth', 'Growth'),
  ('Siddharth Zayn', 'Sample', 'Sample'),
  ('K SONS MARKETING- AMD', 'Growth', 'Growth'),
  ('Wishmakers events Pvt Ltd', 'Sample', 'Sample'),
  ('THE FITNESS HIVE', 'Growth', 'Growth'),
  ('PRAN FITNESS', 'Growth', 'Growth'),
  ('Innomotive Solutions Pvt Ltd', 'Growth', 'Growth'),
  ('MANOJ GOEL AND SONS', 'GT', 'GT'),
  ('GANAPATI FASHIONS  LTD', 'Growth', 'Growth'),
  ('SHREE SHYAM ENTERPRISES-Lucknow', 'Growth', 'Growth'),
  ('KUNNIL MARGIN FREE HYPER MARKET', 'MT', 'MT'),
  ('Snowman Logistics Limited - Tim Horton', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP-VNS', 'Growth', 'Growth'),
  ('ROOP SAGAR FOODWORKS AND TECHNOLOGIES LLP- Bihar', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP- Hyderabad', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP- Palakkad', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP- Guwahati', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP-HP', 'Growth', 'Growth'),
  ('MS THRIVE VENTURES', 'Growth', 'Growth'),
  ('Radisson Blu Hotel, Kaushambi', 'Growth', 'Growth'),
  ('Eastern Officer Commanding, Field Supply Depot ASC (Sevoke)', 'Growth', 'Growth'),
  ('TajSATS Air Catering Ltd., MOPA (GOA)', 'Growth', 'Growth'),
  ('SHREE MARKETING', 'MT', 'MT'),
  ('EIH Associated Hotels Limited-Shimla', 'Growth', 'Growth'),
  ('Hi-Power Food Supliments', 'GT', 'GT'),
  ('Body Whey- Bhatinda', 'GT', 'GT'),
  ('Shambhavi Enterprises', 'MT', 'MT'),
  ('ITC Limited - Cr', 'GT', 'GT'),
  ('Fazzli Agro India Private Limited', 'GT', 'GT'),
  ('Mohammed Ali (MAS Enterprises)', 'GT', 'GT'),
  ('Body Whey - Bathinda', 'GT', 'GT'),
  ('Perfect Point', 'Growth', 'Growth'),
  ('Razorpay Software Pvt Ltd', 'Growth', 'Growth'),
  ('Shree Shyam Enterprises', 'Growth', 'Growth'),
  ('Ganpati Marketing', 'Growth', 'Growth'),
  ('Fitlete Healthcare (Opc) Private Limited', 'Growth', 'Growth'),
  ('Paradise Power Projects', 'Growth', 'Growth'),
  ('Munchbox Frozen Foods Private Limited', 'Growth', 'Growth'),
  ('Urban Wholesale', 'Growth', 'Growth'),
  ('Nutrition Care & Fitness Shop', 'Growth', 'Growth'),
  ('Roosi Brothers - Umesh Chandha', 'Growth', 'Growth'),
  ('Ekatra Collective Private Limited', 'Growth', 'Growth'),
  ('Sunrise Corporation', 'Growth', 'Growth'),
  ('Airplaza Retail Holdings Pvt Ltd', 'MT', 'MT'),
  ('Gpsar Healthcare Limited', 'MT', 'MT'),
  ('Kunnil Hyper Market (Thiruvananthapuram, 695003)', 'MT', 'MT'),
  ('Margin Free Hyper Market (Thiruvananthapuram - 695583)', 'MT', 'MT'),
  ('Optival Health Solutions Pvt Ltd - Medplus', 'MT', 'MT'),
  ('Bharati Enterprises', 'MT', 'MT'),
  ('Kunnil Super Market (Thiruvananthapuram, 695006)', 'MT', 'MT'),
  ('Shri Krishna Enterprises - Haryana', 'MT', 'MT'),
  ('Genie Bazaar Private Limited', 'MT', 'MT'),
  ('Firstclub Technology Private Limited', 'B2B', 'Others'),
  ('OCTAVOS ENTERPRISE SOLUTIONS PVT LTD', 'B2C', 'Smytten'),
  ('SHRI KRISHNA ENTERPRISES', 'MT', 'MT'),
  ('Munch box Frozen Foods Private Limited- BLR', 'Growth', 'Growth'),
  ('Lo Fresh Foods Private Limited-PUNE', 'Growth', 'Growth'),
  ('EKATRA COLLECTIVE PRIVATE  LIMITED', 'Growth', 'Growth'),
  ('Officer Commanding, Field Supply Depot ASC (Chandigarh)', 'Growth', 'Growth'),
  ('CROWN EDIBLES', 'Growth', 'Growth'),
  ('TajSATS Air Catering Ltd - Amristar', 'Growth', 'Growth'),
  ('PLUTOS ONE TECHNOLOGY PRIVATE LIMITED', 'GT', 'GT'),
  ('Munchbox Frozen Foods Private Limited-CHENNAI', 'Growth', 'Growth'),
  ('Munch box Mumbai LLP-PUNE', 'Growth', 'Growth'),
  ('Munch box Frozen Foods Private Limited-BOM', 'Growth', 'Growth'),
  ('Amazon - Replication - DEL4', 'B2C', 'Replication'),
  ('Amazon - Replication - BLR8', 'B2C', 'Replication'),
  ('JIomart - Luhari', 'Replication', 'Replication'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED  (formerly known as Compass Group India Support Services', 'Growth', 'Growth'),
  ('EMPIRE INDUSTRIES LTD-VENDING DIVISION-DEL', 'Growth', 'Growth'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD-WB', 'MT', 'MT'),
  ('FITLETE HEALTHCARE (OPC) PRIVATE LIMITE', 'Growth', 'Growth'),
  ('PIBIT TECHNOLOGIES PRIVATE LIMITED', 'Growth', 'Growth'),
  ('Munchbox Frozen Foods Private Limited-DELHI', 'Growth', 'Growth'),
  ('Kunnil Margin Free Market', 'MT', 'MT'),
  ('Ganpati Enterprise - Pune', 'Growth', 'Growth'),
  ('PARENTS AGENCIES- BHUBANESWAR', 'Growth', 'Growth'),
  ('Natures Basket Limited Gurgaon', 'MT', 'MT'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD (VISHAL MEGA MART)', 'MT', 'MT'),
  ('Mr. Snehashis Sur', 'Sample', 'Sample'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD-Delhi', 'MT', 'MT'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD -DELHI', 'MT', 'MT'),
  ('GPSAR Healthcare Ltd.', 'GT', 'GT'),
  ('Mohammed Ali', 'Sample', 'Sample'),
  ('Nirupama Banerjee', 'Sample', 'Sample'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD-(BLR)', 'MT', 'MT'),
  ('Dr. Sandesh Agarwal', 'Sample', 'Sample'),
  ('Vikas Chaudhary', 'Sample', 'Sample'),
  ('Mr.Krishanu', 'Sample', 'Sample'),
  ('Cult neo gym Dwarka Sec-07', 'Growth', 'Growth'),
  ('Cult Fraser Road - Patna', 'Growth', 'Growth'),
  ('Lo Fresh Foods Private Limited-Mumbai', 'Growth', 'Growth'),
  ('SNV Aviation Private Limited-GAU', 'Growth', 'Growth'),
  ('Sodexo India Services Pvt Ltd-PUNE', 'Growth', 'Growth'),
  ('Hotel Siddharth Paradise', 'Growth', 'Growth'),
  ('SAUKHYAM- GOA', 'Growth', 'Growth'),
  ('BOLAS AGRO PRIVATE LIMITED', 'Sample', 'Sample'),
  ('POPULAR ESSENTIALS INC', 'Sample', 'Sample'),
  ('SRI LAKSHMINARSIMHA AGRO FOODS', 'Sample', 'Sample'),
  ('Sai Excellent print tech', 'Sample', 'Sample'),
  ('Ratna Packaging Unit 1', 'Sample', 'Sample'),
  ('Amcor Flexibles', 'Sample', 'Sample'),
  ('Christ Foods', NULL, NULL),
  ('Aero packaging', 'Sample', 'Sample'),
  ('V2 innovations', NULL, NULL),
  ('Mayur graphics', NULL, NULL),
  ('SRI BHAGAVATHY TRADERS PRIVATE LIMITED', NULL, NULL),
  ('Pellagic Food Ingredients Private Limited', NULL, NULL),
  ('Nikita containers', NULL, NULL),
  ('Shetron', 'Sample', 'Sample'),
  ('Kandala', 'Sample', 'Sample'),
  ('Sukhee', 'Sample', 'Sample'),
  ('Zircon', NULL, NULL),
  ('Embeeflexi', NULL, NULL),
  ('Genesis', NULL, NULL),
  ('Sodexo India Services Private Limited - GA', 'Growth', 'Growth'),
  ('Razorpay Software Limited', 'Growth', 'Growth'),
  ('EDWIN', 'Sample', 'Sample'),
  ('The Oberoi Hotel -Gurgaon', 'Growth', 'Growth'),
  ('VISHVAND ENTERPRISES PRIVATE LIMITED', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED CAFE COFFEE DAY-DIVISION SCM-HQ', 'Growth', 'Growth'),
  ('Risha Global Consumer Solutions LLP', 'Growth', 'Growth'),
  ('COFFEE DAY GLOBAL LIMITED CAFE COFFEE DAY-DIVISION SCM', 'Growth', 'Growth'),
  ('Tim Hortons India', 'Growth', 'Growth'),
  ('PRADEEP AIR CATERERS (UNIT OF HOTEL PRADEEP)', 'Growth', 'Growth'),
  ('Functional & Innovative Foods Pvt Ltd (Rebala)', 'Sample', 'Sample'),
  ('3P paharpur', 'Sample', 'Sample'),
  ('PV Sons Corn Milling Co Pvt Ltd', 'Sample', 'Sample'),
  ('SPICEJET LIMITED', 'Growth', 'Growth'),
  ('Deepak', 'Sample', 'Sample'),
  ('Tapas paul', 'Sample', 'Sample'),
  ('Lalit', 'Sample', 'Sample'),
  ('V. LAXMI NARAYAN REDDY', 'Sample', 'Sample'),
  ('Rishiav Sharma', 'Sample', 'Sample'),
  ('Arvind Kumar', 'Sample', 'Sample'),
  ('RK WORLDINFOCOM PRIVATE LIMITED', 'B2B', 'Others'),
  ('MAS Enterprises', 'MT', 'MT'),
  ('Refoc Trading Company Private Limited', 'MT', 'MT'),
  ('Mahalaxmi Enterprises - Pune', 'MT', 'MT'),
  ('Transformation Formula', 'MT', 'MT'),
  ('Butterscotch', 'MT', 'MT'),
  ('Prabha Enterprises', 'MT', 'MT'),
  ('Resolve Events & Promotions Private Limited', 'Growth', 'Growth'),
  ('Mukesh Trading Co', 'CSD', 'CSD'),
  ('Rk Worldinfocom Private Limited-Dr', 'B2B', 'Amazon Now'),
  ('Delhivery', 'B2C', 'Website'),
  ('TPF Lab LLP', 'Growth', 'Growth'),
  ('ROADRUNNER FOODS PRIVATE LIMITED', 'Growth', 'Growth'),
  ('cult neo Byadarahalli', 'Growth', 'Growth'),
  ('cult neo gym M S Palya', 'Growth', 'Growth'),
  ('Cult neo gym Kaval Byrasandra', 'Growth', 'Growth'),
  ('Junk Free Life Pvt Ltd', 'Growth', 'Growth'),
  ('Cult neo gym Banashankari', 'Growth', 'Growth'),
  ('BAJO FOODS PRIVATE LIMITED-HYD', 'Growth', 'Growth'),
  ('VAGMI FINCORP', 'Growth', 'Growth'),
  ('cult neo gym Adarsh Nagar', 'Growth', 'Growth'),
  ('Sproutlife Foods Private Limited-Delhi', 'Sample', 'Sample'),
  ('Mr. Sudhir Gupta', 'Sample', 'Sample'),
  ('KPKB Mdster Bhandar-Peringome', 'Offline', 'CSD'),
  ('cult neo gym Mukut Bazar', 'Growth', 'Growth'),
  ('Mr.Javed Alam', 'Growth', 'Growth'),
  ('Sodexo India Services Private Limited - KA', 'Growth', 'Growth'),
  ('Sodexo India Services Private LimitedGA', 'Growth', 'Growth'),
  ('Vendiman Private Limited', 'Growth', 'Growth'),
  ('Ali stores', 'Growth', 'Growth'),
  ('Natures Basket Limited-BLR', 'MT', 'MT'),
  ('SREE VEDANTH ENTERPRISES', 'Growth', 'Growth'),
  ('Eesha Groups', 'Growth', 'Growth'),
  ('Parmar caterers', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP- Jharkhand', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP - KA', 'Growth', 'Growth'),
  ('Roop Sagar Foodworks and Technologies LLP - Rajasthan', 'Growth', 'Growth'),
  ('Cult neo gym - Kirloskar Layout', 'Growth', 'Growth'),
  ('ATLYS INDIA PRIVATE LIMITED', 'Growth', 'Growth'),
  ('Nitin Karla', 'Sample', 'Sample'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED - CPU', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED-CHANNAI', 'Growth', 'Growth'),
  ('EIH Limited -- The Oberoi Rajgarh Palace', 'Growth', 'Growth'),
  ('NIBBLISH', 'Growth', 'Growth'),
  ('Chaubey Enterprises', 'Growth', 'Growth'),
  ('Eatgood Technologies Private Limited', 'Growth', 'Growth'),
  ('Mihir Enterprises - Railway', 'Growth', 'Growth'),
  ('ITC LIMITED, FOODS DIVISION (UAE EXPORT)', 'Growth', 'Growth'),
  ('MS AADYA MARKETING SOLUTION', 'Growth', 'Growth'),
  ('AZ Now + First Club', 'B2B', 'AZ Now + First Club'),
  ('Gagneja Agencies', 'MT', 'MT'),
  ('CMUNITY INNOVATIONS PRIVATE LIMITED - DELHI', 'MT', 'MT'),
  ('Lulu International Shopping Malls Pvt Ltd', 'MT', 'MT'),
  ('Cult Neo Gym Ullal', 'Growth', 'Growth'),
  ('Shri Datta Enterprises', 'MT', 'MT'),
  ('Cult Neo Babusapalya', 'Growth', 'Growth'),
  ('Cult Neo Alambagh', 'Growth', 'Growth'),
  ('Master Canteen 04BN PAC Allahabad', 'CSD', 'CSD'),
  ('GET PAZ SOLUTIONS PRIVATE LIMITED', 'Growth', 'Growth'),
  ('Kendriya Police Canteen 35 BN PAC', 'CSD', 'CSD'),
  ('Avijeet Chowdhury', 'MT', 'MT'),
  ('MAGN VENTURE', 'Growth', 'Growth'),
  ('INDWELL RETAIL PRIVATE LIMITED', 'MT', 'MT'),
  ('R&R Consulting', 'Growth', 'Growth'),
  ('Master Bhandar CRPF Tril Ashram, Dhurwa, Ranchi', 'CSD', 'CSD'),
  ('Master Bhandar, KPKB, Group Centre, CRPF, 9th Mile Amerigog', 'CSD', 'CSD'),
  ('Unit Welfare Fund -Dhule', 'GT', 'GT'),
  ('Master Canteen 37 BN PAC', 'CSD', 'CSD'),
  ('MICRO TRADERS', 'Growth', 'Growth'),
  ('Abhay Pathak', 'MT', 'MT'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED (GOOGLE IT SERVICES)', 'Growth', 'Growth'),
  ('SHIVANK FOODS AND SERVICES', 'Growth', 'Growth'),
  ('Venus Logistics Pvt. Ltd.', 'MT', 'MT'),
  ('MASTER BHANDAR GC CRPF KADARPUR GURUGRAM (MB-HR-GUR-GUR-01)', 'CSD', 'CSD'),
  ('GC CRPF Nagpur', 'CSD', 'CSD'),
  ('SRI ENTERPRISES', 'Growth', 'Growth'),
  ('Heisetasse Beverages Pvt. Ltd- BLR', 'Growth', 'Growth'),
  ('Heisetasse Beverages Pvt. Ltd- Mumbai', 'Growth', 'Growth'),
  ('Heisetasse Beverages Pvt. Ltd- Delhi', 'Growth', 'Growth'),
  ('MASTER BHANDAR DTE. GENL. CRPF CGO COMPLEX (MB-DL-CEN-CIV-02)', 'CSD', 'CSD'),
  ('The Chairman Master Canteen GC CRPF, Nagpur', 'CSD', 'CSD'),
  ('Vivek Ratan', 'Sample', 'Sample'),
  ('Koshala agencies private limited', 'Growth', 'Growth'),
  ('KPKB Master Bhandar,CISF 5th Reserve Battalion Indirapuram,', 'CSD', 'CSD'),
  ('Wal-Mart India Pvt. Ltd -DELHI', 'MT', 'MT'),
  ('MASTER BHANDAR CISF UNIT GBS MAHIPALPUR (MB-DL-SOU-KAP-03)', 'CSD', 'CSD'),
  ('CPC MASTER CANTEEN CISF RTC BARWAHA', 'CSD', 'CSD'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-INTEL', 'Growth', 'Growth'),
  ('GURU KRIPA FAST FOOD & CONFERENSAR', 'Growth', 'Growth'),
  ('Cult Neo Gym Nagaram', 'Growth', 'Growth'),
  ('CUSTOMER- SAMPLE-BANGLORE', 'Sample', 'Sample'),
  ('IG BSF GUWAHATI CENTRAL POLICE MASTER CANTEEN', 'CSD', 'CSD'),
  ('Xipher Technologies Llp', 'MT', 'MT'),
  ('Dugar Overseas Pvt. Ltd', 'Sample', 'Sample'),
  ('Jiomart - Bangalore', 'B2B', 'JioMart'),
  ('Rishi', 'CSD', 'CSD'),
  ('SANIL NAIR,', 'CSD', 'CSD'),
  ('S B yadav', 'CSD', 'CSD'),
  ('Zepto Limited', 'Qcom', 'Zepto'),
  ('Blink Commerce Private Limited', 'Qcom', 'Blinkit'),
  ('Lulu Warehouse Coimbatore', 'MT', 'MT'),
  ('SHREE MARUTI INTEGRATED LOGISTICS LIMITED', NULL, NULL),
  ('Reliance Retail Limited-Guwahati', 'MT', 'MT'),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED-NVIDIA GRAPHICS(Pune)', 'Growth', 'Growth'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD-Guwahati', 'MT', 'MT'),
  ('MASTERT BHANDAR CTC SSB SRINAGAR U.K (MB-UK-PAU-SRI-01', NULL, NULL),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED- NVIDIA GRAPHICS(Hyderabad)', 'Growth', 'Growth'),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED- Cloudera Data Platform', 'Growth', 'Growth'),
  ('Shiva Kumar Agarwal', NULL, NULL),
  ('SRI PARSHVA PHARMA DISTRIBUTORS PRIVATE LIMITED', NULL, NULL),
  ('Cult Neo Attibele', 'Growth', 'Growth'),
  ('SANGEETA ENTERPRISES', NULL, NULL),
  ('TCT VENTURES PVT LTD', NULL, NULL),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED- S BALAJI', 'Growth', 'Growth'),
  ('AIRPLAZA RETAIL HOLDINGS PVT LTD -West Bengal', 'MT', 'MT'),
  ('MS. S I A Enterprises', NULL, NULL),
  ('Nykaa E- Retail Limited', NULL, NULL),
  ('Airplaza Retail Holdings Pvt Ltd-ODISHA', 'MT', 'MT'),
  ('Nykaa E-Retail Limited (Superstore) - West Bengal', 'MT', 'MT'),
  ('EKAAYA NETWORK PRIVATE LIMITED (M2 Vending- Hyd)', 'Growth', 'Growth'),
  ('MAHAVIRA MARKETING', NULL, NULL),
  ('SANJEEV SANDHWAR', NULL, NULL),
  ('TCT Ventures Private Limited', NULL, NULL),
  ('Krishanu Singh', NULL, NULL),
  ('COTHAS COFFEE CO', 'Growth', 'Growth'),
  ('Wal-Mart India Pvt Ltd', NULL, NULL),
  ('SUPPLEMENT ZONE', NULL, NULL),
  ('APOLLO HEALTHCO LIMITED - ASSAM', NULL, NULL),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED - Google India BLR', 'Growth', 'Growth'),
  ('MASTER BHANDAR 22 BN ITBP TIGRI CAMP (MB-DL-SOU-HAU-01)', NULL, NULL),
  ('BOTTLE LAB TECHNOLOGIES PRIVATE LIMITED- BHOJANN FOODS', 'Growth', 'Growth'),
  ('RAGHAV ENTERPRISES', NULL, NULL),
  ('N.G.R Enterprises', NULL, NULL),
  ('COMPASS INDIA FOOD SERVICES PRIVATE LIMITED  - Intel', 'Growth', 'Growth'),
  ('PRINCE SALT TRADERS', NULL, NULL),
  ('SUBHASH TRADING CO', NULL, NULL),
  ('SANJEEV SANDHWAR,', NULL, NULL),
  ('Uppal Traders', NULL, NULL),
  ('TREASUREHUNT RETAIL PRIVATE LIMITED', NULL, NULL),
  ('SRISINHALA ENTERPRISES', NULL, NULL),
  ('GUPTA ENTERPRISE', NULL, NULL),
  ('SNV Aviation Private Limited-MAA', 'Growth', 'Growth'),
  ('RAZORPAY SOFTWARE  LIMITED', 'Growth', 'Growth'),
  ('ITC Limited- Kolkata', NULL, NULL),
  ('Nykaa E-Retail Limited (Superstore)', NULL, NULL),
  ('ONTIME OFFICE SOLUTIONS', NULL, NULL),
  ('SHREE KHATU SHYAM ENTERPRISES', NULL, NULL),
  ('Air India Express Limited-TRV', NULL, NULL)
on conflict (customer) do update set channel=excluded.channel, platform=excluded.platform;

-- warehouses: 24
insert into public.movement_warehouse_map (warehouse, channel) values
  ('ITC Limited - Bangalore (Dummy Account)', 'GT'),
  ('Mithra Associates', 'MT'),
  ('Kolkata CFA', 'MT'),
  ('Emiza 3 Warehouse', 'B2C'),
  ('Emiza -Delhi', 'B2C'),
  ('EMIZA - Mumbai', 'B2C'),
  ('Ahmedabad CFA', 'MT'),
  ('Mumbai CFA', 'MT'),
  ('Pune CFA', 'MT'),
  ('Kerala CFA', 'MT'),
  ('BENGALURU CFA', 'MT'),
  ('Head Office', 'Sample'),
  ('Delhi -CFA GHEVRA', 'MT'),
  ('Prozo - Hoskote', 'B2C'),
  ('Chennai CFA', 'MT'),
  ('PMR - Nelamangala', 'B2C'),
  ('Online Kolkata CFA', 'Qcom'),
  ('Online Delhi -CFA GHEVRA', 'Qcom'),
  ('Online Mumbai CFA', 'Qcom'),
  ('Online Pune CFA', 'Qcom'),
  ('Lucknow CFA', 'MT'),
  ('Cuttack CFA', 'MT'),
  ('Guwahati CFA', 'MT'),
  ('Indore CFA', 'MT')
on conflict (warehouse) do update set channel=excluded.channel;
